spring:
  application:
    name: oauth2-restclient-demo
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          spotify:
            tokenUri: https://accounts.spotify.com/api/token
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update