spring:
  datasource:
    url: jdbc:h2:mem:mydb;MODE=POSTGRESQL;INIT=CREATE SCHEMA IF NOT EXISTS spotify;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      data-locations: classpath:data-h2.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: spotify
    open-in-view: false
  h2:
    console:
      enabled: true